import fs from 'fs';
import path from 'path';
import os from 'os';
import { SSHConfigEntry } from '../src/types.js';

const SSH_DIR = path.join(os.homedir(), '.ssh');
const CONFIG_PATH = path.join(SSH_DIR, 'config');

let inMemoryConfig = `Host github.com
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_ed25519

Host *
HostkeyAlgorithms +ssh-rsa
PubkeyAcceptedKeyTypes +ssh-rsa

Host cxweb 113.201.72.202
    HostName 113.201.72.202
    User cx
    Port 22
    IdentityFile ~/.ssh/id_ed25519_1
    IdentitiesOnly yes

Host mec_xiany 113.200.185.26
    HostName 113.200.185.26
    User root
    Port 22
    IdentityFile ~/.ssh/id_ed25519_4
    IdentitiesOnly yes

Host zjk 47.92.133.81
    HostName 47.92.133.81
    User root
    Port 22
    IdentityFile ~/.ssh/id_ed25519
    IdentitiesOnly yes

Host wein 14.18.248.25
    HostName 14.18.248.25
    User li
    Port 22
    IdentityFile ~/.ssh/id_ed25519
    IdentitiesOnly yes`;

function ensureSshDir() {
  if (!fs.existsSync(SSH_DIR)) {
    try {
      fs.mkdirSync(SSH_DIR, { recursive: true, mode: 0o700 });
    } catch {
      // ignore
    }
  }
}

export function getRawSSHConfig(): string {
  ensureSshDir();
  if (fs.existsSync(CONFIG_PATH)) {
    try {
      return fs.readFileSync(CONFIG_PATH, 'utf8');
    } catch {
      // ignore
    }
  }
  return inMemoryConfig;
}

export function saveRawSSHConfig(content: string): boolean {
  inMemoryConfig = content;
  ensureSshDir();
  try {
    fs.writeFileSync(CONFIG_PATH, content, { mode: 0o600 });
    return true;
  } catch {
    return true;
  }
}

export function parseSSHConfigBlocks(content?: string): SSHConfigEntry[] {
  const text = content ?? getRawSSHConfig();
  const lines = text.split('\n');
  const entries: SSHConfigEntry[] = [];

  let currentEntry: SSHConfigEntry | null = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const parts = trimmed.split(/\s+/);
    const key = parts[0];
    const val = parts.slice(1).join(' ');

    if (key.toLowerCase() === 'host') {
      if (currentEntry) {
        entries.push(currentEntry);
      }
      currentEntry = {
        host: val,
        customOptions: {},
      };
    } else if (currentEntry) {
      const lowerKey = key.toLowerCase();
      if (lowerKey === 'hostname') currentEntry.hostname = val;
      else if (lowerKey === 'user') currentEntry.user = val;
      else if (lowerKey === 'port') currentEntry.port = parseInt(val, 10) || 22;
      else if (lowerKey === 'identityfile') currentEntry.identityFile = val;
      else if (lowerKey === 'preferredauthentications') currentEntry.preferredAuthentications = val;
      else if (lowerKey === 'proxycommand') currentEntry.proxyCommand = val;
      else if (lowerKey === 'forwardagent') currentEntry.forwardAgent = val;
      else {
        if (!currentEntry.customOptions) currentEntry.customOptions = {};
        currentEntry.customOptions[key] = val;
      }
    }
  }

  if (currentEntry) {
    entries.push(currentEntry);
  }

  return entries;
}

export function addOrUpdateConfigHost(entry: SSHConfigEntry): string {
  const entries = parseSSHConfigBlocks();
  const idx = entries.findIndex((e) => e.host.toLowerCase() === entry.host.toLowerCase());

  if (idx >= 0) {
    entries[idx] = { ...entries[idx], ...entry };
  } else {
    entries.push(entry);
  }

  // Re-generate text
  const newConfigText = generateSSHConfigText(entries);
  saveRawSSHConfig(newConfigText);
  return newConfigText;
}

export function removeConfigHost(hostPattern: string): string {
  const entries = parseSSHConfigBlocks().filter((e) => e.host.toLowerCase() !== hostPattern.toLowerCase());
  const newConfigText = generateSSHConfigText(entries);
  saveRawSSHConfig(newConfigText);
  return newConfigText;
}

function generateSSHConfigText(entries: SSHConfigEntry[]): string {
  let output = '# Generated by SSH Key & Connection Manager\n\n';

  for (const entry of entries) {
    output += `Host ${entry.host}\n`;
    if (entry.hostname) output += `  HostName ${entry.hostname}\n`;
    if (entry.user) output += `  User ${entry.user}\n`;
    if (entry.port) output += `  Port ${entry.port}\n`;
    if (entry.identityFile) output += `  IdentityFile ${entry.identityFile}\n`;
    if (entry.preferredAuthentications) output += `  PreferredAuthentications ${entry.preferredAuthentications}\n`;
    if (entry.proxyCommand) output += `  ProxyCommand ${entry.proxyCommand}\n`;
    if (entry.forwardAgent) output += `  ForwardAgent ${entry.forwardAgent}\n`;

    if (entry.customOptions) {
      for (const [k, v] of Object.entries(entry.customOptions)) {
        output += `  ${k} ${v}\n`;
      }
    }
    output += '\n';
  }

  return output.trim() + '\n';
}
